[package]
name = "rchip8-wasm"
version = "0.1.0"
authors = ["landhb <landherrb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rchip8 = {path ="../lib",version = "0.1.0"}
